#+title: Anthony Burton’s internet site
#+date:
#+OPTIONS: toc:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="typesettings.css"/>


Anthony Glyn Burton has worked as a dockmaster, bartender, hockey referee, baby food marketer,  driving range ball picker-upper, journalist, editor, cultural events producer, and digital researcher. He is now a SSHRC Joseph Armand Bombardier Ph.D. scholar at Simon Fraser University’s Communications Department and a doctoral researcher at the Digital Democracies Institute, located in Vancouver, BC. Anthony joined SFU after finishing his master’s degree at York and [[https://yellowheadinstitute.org/2021/05/11/welcome-to-x-university-an-open-letter-to-the-community-from-indigenous-students/]]][X University]]’s Joint Program in Communication & Culture, where he first joined the Infoscape Lab and the Open Intelligence Lab (OILab). He received his H.B.A. in English and Philosophy from Victoria University in the University of Toronto and continues to research computation, politics, code, and rationality. His M.A. thesis, full C.V., and other links are below.

+ [[file:cv.html][curriculum vitae]]
+ [[file:about.html][about]]
+ [[file:digital-methods.html][a list of digital methods resources]]
+ [[https://www.flickr.com/people/holeyship/][photography]]
+ [[https://www.gitlab.com/anthbrtn/][code]]
+ [[https://www.twitter.com/anthbrtn/][tweets]]
+ [[https://www.zotero.org/anthbrtn/library/][my zotero library]]
